# yaml-language-server: $schema=https://promptfoo.dev/config-schema.json
targets:
  - file://custom-dib-provider.js
providers:
  - id: 'file://custom-dib-provider.js'
    config:
      temperature: 0.7
      max_tokens: 1500
      top_p: 0.95
      frequency_penalty: 0
      presence_penalty: 0
